[bumpver]
current_version = "2.2.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message  = "Bump version {old_version} -> {new_version}"
commit = false
tag = false
push = false

[bumpver.file_patterns]
"bumpver.toml" = ['current_version = "{version}"']
"setup.py" = ["{version}"]
"docs/source/conf.py" = ['release = "{version}"']

